
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 26 17:15:10 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 12;
  public static final int IDENT = 30;
  public static final int PERCENT = 24;
  public static final int PLUS = 17;
  public static final int RBRACE = 4;
  public static final int RPAREN = 7;
  public static final int EQUAL = 8;
  public static final int CHARACTER = 20;
  public static final int SEMI = 5;
  public static final int NAMESPACE = 28;
  public static final int RETURN = 9;
  public static final int DOUBLECOLON = 11;
  public static final int LBRACKET = 25;
  public static final int LPAREN = 6;
  public static final int DOUBLEPLUS = 16;
  public static final int LBRACE = 3;
  public static final int RBRACKET = 27;
  public static final int BOOLEAN = 21;
  public static final int COMMA = 15;
  public static final int NUMBER = 29;
  public static final int EOF = 0;
  public static final int DIV = 22;
  public static final int PROG = 2;
  public static final int DOUBLEMINUS = 10;
  public static final int MINUS = 23;
  public static final int CONST = 26;
  public static final int PRINT = 19;
  public static final int error = 1;
  public static final int NEW = 13;
  public static final int VOID = 18;
  public static final int MUL = 14;
}

