
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 22 20:02:39 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 29;
  public static final int COLONCOLON = 21;
  public static final int IDENT = 34;
  public static final int PERCENT = 16;
  public static final int PLUS = 11;
  public static final int RBRACE = 4;
  public static final int RPAREN = 7;
  public static final int EQUAL = 12;
  public static final int CHARACTER = 20;
  public static final int SEMI = 5;
  public static final int NAMESPACE = 31;
  public static final int QUOTATION = 28;
  public static final int RETURN = 10;
  public static final int MINUSMINUS = 23;
  public static final int COLON = 32;
  public static final int LBRACKET = 25;
  public static final int LPAREN = 6;
  public static final int LBRACE = 3;
  public static final int RBRACKET = 30;
  public static final int BOOLEAN = 14;
  public static final int COMMA = 8;
  public static final int DOUBLEQUOTES = 27;
  public static final int NUMBER = 33;
  public static final int EOF = 0;
  public static final int DIV = 18;
  public static final int PROG = 2;
  public static final int PLUSPLUS = 22;
  public static final int MINUS = 19;
  public static final int CONST = 24;
  public static final int DOT = 17;
  public static final int PRINT = 9;
  public static final int error = 1;
  public static final int NEW = 15;
  public static final int MUL = 26;
  public static final int VOID = 13;
}

